version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      # POSTGRES_USER: postgres
      - POSTGRES_PASSWORD=postgrespw
      # POSTGRES_DB: auction
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata: