FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /app

EXPOSE 80

# Copy csproj and restore as distinct layers
# User of the same COPY command for all projects to take advantage of caching
COPY Auctioniest.sln Auctioniest.sln
COPY src/AuctionService/AuctionService.csproj src/AuctionService/AuctionService.csproj
COPY src/SearchService/SearchService.csproj src/SearchService/SearchService.csproj
COPY src/GatewayService/GatewayService.csproj src/GatewayService/GatewayService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj


# Restore package dependencies
RUN dotnet restore Auctioniest.sln

# Copy everything else and build
COPY src/GatewayService src/GatewayService
WORKDIR /app/src/GatewayService
RUN dotnet publish -c Release -o /app/src/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT [ "dotnet", "GatewayService.dll" ]